<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>json</name>
   <tag></tag>
   <elementGuidId>f491eac4-f948-42ae-bd9d-5c2eedd7ee6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::pre[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>pre</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>{&quot;menuSeleccionado&quot;:&quot;cashflow&quot;,&quot;anioInicial&quot;:&quot;2020&quot;,&quot;mesInicial&quot;:&quot;01&quot;,&quot;tipoDeCambio&quot;:1,&quot;tipoDeCambioCashflow&quot;:1,&quot;tipoDeCambioMoneda&quot;:{&quot;id&quot;:1,&quot;abreviacion&quot;:&quot;Q&quot;,&quot;nombre&quot;:&quot;Quetzal&quot;,&quot;pais&quot;:&quot;Guatemala&quot;,&quot;monedaBancoGuatemalaId&quot;:1,&quot;simbolo&quot;:&quot;Q&quot;,&quot;tipoDeCambio&quot;:&quot;1.00000&quot;},&quot;datosTipoDeCambio&quot;:[1,7.695501333333332,7.695501333333332,7.695501333333332,7.695501333333332,7.695501333333332,7.695501333333332,7.695501333333332,7.695501333333332,7.695501333333332,7.695501333333332,7.695501333333332,7.695501333333332],&quot;datosMoneda&quot;:{&quot;id&quot;:2,&quot;abreviacion&quot;:&quot;USD&quot;,&quot;nombre&quot;:&quot;D\u00f3lar&quot;,&quot;pais&quot;:&quot;Estados Unidos de Am\u00e9rica&quot;,&quot;monedaBancoGuatemalaId&quot;:2,&quot;simbolo&quot;:&quot;$&quot;},&quot;titulo&quot;:&quot;AUTOMATA S.A. - Cashflow&quot;,&quot;nombreTablaResumen&quot;:&quot;Resumen&quot;,&quot;nombreTablaEjecutado&quot;:&quot;Ejecutado&quot;,&quot;nombreTablaProyectado&quot;:&quot;Proyectado&quot;,&quot;columnasEditables&quot;:true}</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/pre[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::pre[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::pre[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//pre</value>
   </webElementXpaths>
</WebElementEntity>
