<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_menuSeleccionadoinicioanioInicial2020mesInicial01tipoDeCambio76779tituloAUTOMATA SAhtml1body1</name>
   <tag></tag>
   <elementGuidId>4f7201e6-6f77-4d1f-b01d-de3ee680c075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>{&quot;menuSeleccionado&quot;:&quot;inicio&quot;,&quot;anioInicial&quot;:&quot;2020&quot;,&quot;mesInicial&quot;:&quot;01&quot;,&quot;tipoDeCambio&quot;:7.6779,&quot;titulo&quot;:&quot;AUTOMATA S.A.&quot;}/html[1]/body[1]</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
   </webElementXpaths>
</WebElementEntity>
